#ifndef _INDOOR_UWB_TYPES_H
#define _INDOOR_UWB_TYPES_H

enum ControllerType {
	CONTROLLER_WIFI,
	CONTROLLER_DW1000,
	CONTROLLER_ESPNOW,
	CONTROLLER_WEB,
	CONTROLLER_OTA,
	CONTROLLER_STORAGE,
	CONTROLLER_TAG,
	CONTROLLER_VOID
};

#endif
